{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "continuum-infra.kafka.fullname" . }}-headless
  labels:
    {{- include "continuum-infra.componentLabels" (dict "context" $ "component" "kafka" "extra" .Values.kafka.labels) | nindent 4 }}
  {{- with (include "continuum-infra.componentAnnotations" (dict "context" $ "extra" .Values.kafka.annotations)) }}
  annotations:
    {{- nindent 4 . }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 19092
      targetPort: broker
      protocol: TCP
      name: broker
    - port: 9093
      targetPort: controller
      protocol: TCP
      name: controller
  selector:
    app.kubernetes.io/component: kafka
    {{- include "continuum-infra.selectorLabels" . | nindent 4 }}
{{- end }}
