{{- if .Values.keycloak.enabled }}
{{- $fullname := include "continuum-sso.fullname" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-keycloak
  labels:
    {{- include "continuum-sso.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
    - port: {{ .Values.keycloak.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "continuum-sso.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
{{- end }}

