{{- if .Values.schemaRegistry.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "continuum-infra.schema-registry.fullname" . }}
  labels:
    app.kubernetes.io/component: schema-registry
    {{- include "continuum-infra.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.schemaRegistry.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: schema-registry
    {{- include "continuum-infra.selectorLabels" . | nindent 4 }}
{{- end }}
