{{- if and .Values.minio.enabled (not .Values.minio.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "continuum-infra.minio.secretName" . }}
  labels:
    app.kubernetes.io/component: minio
    {{- include "continuum-infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-user: {{ required "minio.auth.rootUser is required" .Values.minio.auth.rootUser | quote }}
  root-password: {{ required "minio.auth.rootPassword is required" .Values.minio.auth.rootPassword | quote }}
{{- end }}
