{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "continuum-infra.minio.fullname" . }}
  labels:
    app.kubernetes.io/component: minio
    {{- include "continuum-infra.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: api
      protocol: TCP
      name: api
    - port: 9001
      targetPort: console
      protocol: TCP
      name: console
  selector:
    app.kubernetes.io/component: minio
    {{- include "continuum-infra.selectorLabels" . | nindent 4 }}
{{- end }}
