{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "continuum-infra.postgresql.secretName" . }}
  labels:
    {{- include "continuum-infra.componentLabels" (dict "context" $ "component" "postgresql" "extra" .Values.postgresql.labels) | nindent 4 }}
  {{- with (include "continuum-infra.componentAnnotations" (dict "context" $ "extra" .Values.postgresql.annotations)) }}
  annotations:
    {{- nindent 4 . }}
  {{- end }}
type: Opaque
stringData:
  postgres-password: {{ required "postgresql.auth.postgresPassword is required" .Values.postgresql.auth.postgresPassword | quote }}
  continuum-db-user: {{ .Values.postgresql.auth.continuumUser | quote }}
  continuum-db-password: {{ required "postgresql.auth.continuumPassword is required" .Values.postgresql.auth.continuumPassword | quote }}
  continuum-db-name: {{ .Values.postgresql.auth.continuumDatabase | quote }}
{{- end }}
