{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "continuum-infra.postgresql.fullname" . }}
  labels:
    app.kubernetes.io/component: postgresql
    {{- include "continuum-infra.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.service.port | default 5432 }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/component: postgresql
    {{- include "continuum-infra.selectorLabels" . | nindent 4 }}
{{- end }}
