{{- if .Values.clusterManager.overlays.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "continuum-platform.cluster-manager.fullname" . }}-overlays
  labels:
    app.kubernetes.io/component: cluster-manager
    {{- include "continuum-platform.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.clusterManager.overlays.files }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
{{- end }}
