{{- if .Values.clusterManager.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "continuum-platform.cluster-manager.fullname" . }}
  labels:
    app.kubernetes.io/component: cluster-manager
    {{- include "continuum-platform.labels" . | nindent 4 }}
{{- end }}

