{{- if .Values.orchestrationService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "continuum-platform.orchestration-service.fullname" . }}
  labels:
    app.kubernetes.io/component: orchestration-service
    {{- include "continuum-platform.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.orchestrationService.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: orchestration-service
    {{- include "continuum-platform.selectorLabels" . | nindent 4 }}
{{- end }}
