{{- if .Values.mosquitto.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "continuum-infra.mosquitto.fullname" . }}-config
  labels:
    {{- include "continuum-infra.componentLabels" (dict "context" $ "component" "mosquitto" "extra" .Values.mosquitto.labels) | nindent 4 }}
  {{- with (include "continuum-infra.componentAnnotations" (dict "context" $ "extra" .Values.mosquitto.annotations)) }}
  annotations:
    {{- nindent 4 . }}
  {{- end }}
data:
  mosquitto.conf: |
    persistence {{ .Values.mosquitto.config.persistence }}
    persistence_location /mosquitto/data/
    log_dest file /mosquitto/log/mosquitto.log

    listener {{ .Values.mosquitto.config.tcpPort | default 1883 }}
    listener {{ .Values.mosquitto.config.websocketPort | default 1884 }}
    protocol websockets
    allow_anonymous {{ .Values.mosquitto.config.allowAnonymous }}
{{- end }}
