{{- $tc := index .Values "theia-cloud" -}}
{{- if $tc.enabled }}
apiVersion: theia.cloud/v1beta10
kind: AppDefinition
metadata:
  name: {{ $tc.workbench.appDefinition.name }}
  labels:
    app.kubernetes.io/component: workbench
    {{- include "continuum-infra.labels" . | nindent 4 }}
spec:
  name: {{ $tc.workbench.appDefinition.name }}
  image: "{{ $tc.workbench.image.repository }}:{{ $tc.workbench.image.tag }}"
  imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
  port: {{ $tc.workbench.port }}
  uid: {{ $tc.workbench.uid }}
  ingressname: {{ $tc.workbench.ingressname }}
  minInstances: {{ $tc.workbench.minInstances }}
  maxInstances: {{ $tc.workbench.maxInstances }}
  timeout: {{ $tc.workbench.timeout }}
  requestsCpu: {{ $tc.workbench.resources.requestsCpu | quote }}
  requestsMemory: {{ $tc.workbench.resources.requestsMemory | quote }}
  limitsCpu: {{ $tc.workbench.resources.limitsCpu | quote }}
  limitsMemory: {{ $tc.workbench.resources.limitsMemory | quote }}
  downlinkLimit: {{ $tc.workbench.downlinkLimit }}
  uplinkLimit: {{ $tc.workbench.uplinkLimit }}
  mountPath: {{ $tc.workbench.mountPath | quote }}
  monitor:
    port: {{ $tc.workbench.monitor.port }}
    activityTracker:
      timeoutAfter: {{ $tc.workbench.monitor.activityTracker.timeoutAfter }}
      notifyAfter: {{ $tc.workbench.monitor.activityTracker.notifyAfter }}
{{- end }}
